a=int(input("Enter first number:"))
b=int(input("Enter second number:"))
print("First number:",a)
print("Second number:",b)
print("Addition:",a+b)  
print("Subtraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Floor Division:",a//b)
print("Modulus:",a%b)