num=int(input("Enter an integer:"))
print("Integer:",num)
pi=float(input("Enter a float number:"))
print("Float number:",pi)
name=input("Enter a string:")
print("String:",name)
is_easy=input("Enter True or False:")
print("Boolean:",is_easy)
fruits=input("Enter multiple fruits separated by commas:").split(',')
print("List:",fruits)
colors=tuple(input("Enter multiple colors separated by commas:").split(','))
print("Tuple:",colors) 
unique_numbers=set(input("Enter multiple numbers separated by commas:").split(','))
print("Set:",unique_numbers)
student={"name":input("Enter student name:"),"age":int(input("Enter student age:"))}
print("Dictionary:",student)